benchmark:
  sut: "MongoDB"
  nodes:
    - "34.76.114.204"
  threads: 16
  random_seed: 444

queryConfigs:

  # Temporal queries
  # use
  - name: countActiveFlightsInPeriod
    use: True
    type: temporal
    repetition: 50
    parameters:
      - period_long
  # use
  - name: locationOfAirplaneAtInstant
    use: True
    type: temporal
    repetition: 50
    parameters:
      - instant
  # use
  - name: airportUtilizationInPeriod
    use: True
    type: temporal
    repetition: 50
    parameters:
      - period_medium

  # Spatial queries
  # use
  - name: countFlightsInCounties
    use: True
    type: spatial
    repetition: 50
    parameters:
      - county

  # use
  - name: flightsCloseToMainCitiesLowAltitude
    use: True
    type: spatial
    repetition: 50
    parameters:
      - low_altitude
      - radius

  # use
  - name: flightClosestToPoint
    use: True
    type: spatial
    repetition: 50
    parameters:
      - point
      - distance

  # spatiotemporal queries
  - name: flightsInCountyInPeriod
    use: True
    type: spatiotemporal
    repetition: 50
    parameters:
      - period_short
      - county

  # use
  - name: countFlightsAtInstantInDistricts
    use: True
    type: spatiotemporal
    repetition: 50
    parameters:
      - instant

  # use
  - name: inCityRadiusInPeriod
    use: True
    type: spatiotemporal
    repetition: 50
    parameters:
      - period_medium
      - city
      - radius

  # use
  - name: flightDurationInMunicipalityLowAltitudeInPeriod
    use: True
    type: spatial-temporal
    repetition: 50
    parameters:
      - period_short
      - municipality
      - low_altitude

  # use
  - name: flightsInMunicipalityLowAltitudeInPeriod
    use: True
    type: spatial-temporal
    repetition: 50
    parameters:
      - period_short
      - municipality
      - low_altitude

  # use
  - name: averageHourlyFlightsDuringDayInMunicipality
    use: True
    type: spatiotemporal
    repetition: 50
    parameters:
      - day
      - municipality
  # use
  - name: flightsWithLocalOriginDestinationInPeriodInCounty
    use: True
    type: spatiotemporal
    repetition: 50
    parameters:
      - period_medium
      - county


  # currently not in use
  - name: averageHourlyFlightsDuringDay
    use: False
    type: temporal
    repetition: 50
    parameters:
      - day

  - name: flightsWithLocalOriginDestinationInPeriod
    use: False
    type: temporal
    repetition: 2
    parameters:
      - period_short

  - name: flightsInCityRadius
    use: False
    type: spatial
    repetition: 2
    parameters:
      - city
      - radius

  - name: flightsIntersectingMunicipalities
    use: False
    type: spatial
    repetition: 2
    parameters:
      - municipality