benchmark:
  sut: "MongoDB"
  mixed: False
  nodes:
    - "34.78.92.98"
    - "35.205.167.189"
    - "146.148.118.85"
  threads: 16
  test: False
  random_seed: 1500

queryConfigs:

  # Temporal queries
  # use
  - name: countActiveFlightsInPeriod
    use: False
    type: temporal
    repetition: 20
    parameters:
      - period_medium
  # use
  - name: locationOfAirplaneAtInstant
    use: False
    type: temporal
    repetition: 20
    parameters:
      - instant
  # use
  - name: airportUtilizationInPeriod
    use: False
    type: temporal
    repetition: 20
    parameters:
      - period_short

  # Spatial queries
  # use
  - name: countFlightsInCounties
    use: True
    type: spatial
    repetition: 100
    parameters:
      - county

  # use
  - name: flightsCloseToMainCitiesLowAltitude
    use: True
    type: spatial
    repetition: 100
    parameters:
      - low_altitude
      - radius

  # use
  - name: flightClosestToPoint
    use: True
    type: spatial
    repetition: 100
    parameters:
      - point
      - distance

  # spatiotemporal queries
  - name: flightsInCountyInPeriod
    use: False
    type: spatiotemporal
    repetition: 100
    parameters:
      - period_medium
      - county

  # use
  - name: countFlightsAtInstantInDistricts
    use: False
    type: spatiotemporal
    repetition: 100
    parameters:
      - instant

  # use
  - name: inCityRadiusInPeriod
    use: False
    type: spatiotemporal
    repetition: 100
    parameters:
      - period_medium
      - city
      - radius

  # use
  - name: flightDurationInMunicipalityLowAltitudeInPeriod
    use: False
    type: spatial-temporal
    repetition: 100
    parameters:
      - period_medium
      - municipality
      - low_altitude

  # use
  - name: averageHourlyFlightsDuringDayInMunicipality
    use: False
    type: spatiotemporal
    repetition: 100
    parameters:
      - day
      - municipality

  # use
  - name: flightsWithLocalOriginDestinationInPeriodInCounty
    use: False
    type: spatiotemporal
    repetition: 100
    parameters:
      - period_short
      - county
