benchmark:
  sut: "MongoDB"
  nodes:
    - "35.195.232.78"
    - "35.195.255.122"
    - "34.38.65.14"
  threads: 2
  random_seed: 123

queryConfigs:

  # Temporal queries (5 functioning queries)
  - name: countActiveFlightsInPeriod
    use: True
    type: temporal
    mongodbQuery: abc
    repetition: 2
    parameters:
      - period

  - name: locationOfAirplaneAtInstant
    use: True
    type: temporal
    mongodbQuery: abc
    repetition: 2
    parameters:
      - instant

  - name: averageHourlyFlightsDuringDay
    use: True
    type: temporal
    mongodbQuery: abc
    repetition: 2
    parameters:
      - day

  - name: flightsWithLocalOriginDestinationInPeriod
    use: True
    type: temporal
    mongodbQuery: abc
    repetition: 2
    parameters:
      - period_short

  - name: airportUtilizationInPeriod
    use: True
    type: temporal
    mongodbQuery: abc
    repetition: 2
    parameters:
      - period_medium

  # Spatial queries (7 functioning queries)
  - name: flightsInCityRadius
    use: True
    type: spatial
    mongodbQuery: abc
    repetition: 2
    parameters:
      - city
      - radius

  - name: flightsIntersectingMunicipalities
    use: True
    type: spatial
    mongodbQuery: abc
    repetition: 2
    parameters:
      - municipality

  - name: countFlightsInCounties
    use: True
    type: spatial
    mongodbQuery: abc
    repetition: 2
    parameters:
      - county

  - name: flightsCloseToMainCitiesLowAltitude
    use: True
    type: spatial
    mongodbQuery: abc
    repetition: 2
    parameters:
      - low_altitude
      - radius

  - name: countiesLandingsDepartures
    use: True
    type: spatial
    mongodbQuery: abc
    repetition: 2
    parameters:
      - county

  - name: flightClosestToPoint
    use: True
    type: spatial
    mongodbQuery: abc
    repetition: 2
    parameters:
      - point
      - distance

  # spatiotemporal queries (7 functioning queries)
  - name: flightsInCountyInPeriod
    use: True
    type: spatiotemporal
    mongodbQuery: abc
    repetition: 2
    parameters:
      - period
      - county

  - name: pairOfFlightsInMunicipalityInPeriod
    use: True
    type: spatio-temporal
    mongodbQuery: abc
    repetition: 2
    parameters:
      - period_short
      - municipality

  - name: countFlightsAtInstantInDistricts
    use: True
    type: spatio-temporal
    mongodbQuery: abc
    repetition: 2
    parameters:
      - instant

  - name: inCityRadiusInPeriod
    use: True
    type: spatio-temporal
    mongodbQuery: abc
    repetition: 2
    parameters:
      - period
      - city
      - radius

  - name: flightDurationInMunicipalityLowAltitudeInPeriod
    use: True
    type: spatial-temporal
    mongodbQuery: abc
    repetition: 2
    parameters:
      - period
      - municipality
      - low_altitude

  - name: averageHourlyFlightsDuringDayInCounty
    use: True
    type: spatiotemporal
    mongodbQuery: abc
    repetition: 2
    parameters:
      - day
      - county

  - name: flightsWithLocalOriginDestinationInPeriodInCounty
    use: True
    type: spatio-temporal
    mongodbQuery: abc
    repetition: 2
    parameters:
      - period
      - county





# queries not being used

  # bisher noch nicht implementiert (auch nicht in MobiltiyDB)
  - name: FlightDistanceInCounties
    use: False
    type: spatial
    mongodbQuery: abc
    repetition: 2
    parameters:
      - county
      - type

# takes too long to execute
  - name: flightsOnlyInOneDistrict
    use: False
    type: spatial
    mongodbQuery: abc
    repetition: 2
    parameters:
      - district


# takes too long to execute (complex implementation)
  - name: crossedCountiesInPeriodWithDestination
    use: False
    type: spatiotemporal
    mongodbQuery: abc
    repetition: 10
    parameters:
      - period_short

  # takes very long to execute as filtering based on time or space is not possible before calculating distances of each pair of flightpoints
  - name: closePairOfPlanes
    use: False
    type: spatiotemporal
    mongodbQuery: abc
    repetition: 1000
    parameters:
      - county




  - name: flightsInCountyInPeriodTs
    use: False
    type: spatiotemporal
    mongodbQuery: abc
    repetition: 100
    parameters:
      - period
      - county




  # dont use (already better in spatio temporal)
  - name: flightTimeLowAltitude
    use: False
    type: temporal
    mongodbQuery: abc
    repetition: 2
    parameters:
      - period_short








