val municipalities = listOf(
    mapOf("name" to "Gem Brilon"),
    mapOf("name" to "Gem Kaarst"),
    mapOf("name" to "Gem Castrop-Rauxel"),
    mapOf("name" to "Gem Stemwede"),
    mapOf("name" to "Gem Waldfeucht"),
    mapOf("name" to "Gem Weeze"),
    mapOf("name" to "Gem Kleve"),
    mapOf("name" to "Gem Ahaus"),
    mapOf("name" to "Gem Drensteinfurt"),
    mapOf("name" to "Gem Werther (Westf.)"),
    mapOf("name" to "Gem Mettmann"),
    mapOf("name" to "Gem Gummersbach"),
    mapOf("name" to "Gem Nordkirchen"),
    mapOf("name" to "Gem Geilenkirchen"),
    mapOf("name" to "Gem Hennef (Sieg)"),
    mapOf("name" to "Gem Kempen"),
    mapOf("name" to "Gem Aachen"),
    mapOf("name" to "Gem Siegburg"),
    mapOf("name" to "Gem Marsberg"),
    mapOf("name" to "Gem Velbert"),
    mapOf("name" to "Gem Bad Honnef"),
    mapOf("name" to "Gem Schwalmtal"),
    mapOf("name" to "Gem Muenster"),
    mapOf("name" to "Gem Odenthal"),
    mapOf("name" to "Gem Haan"),
    mapOf("name" to "Gem Breckerfeld"),
    mapOf("name" to "Gem Lippetal"),
    mapOf("name" to "Gem Salzkotten"),
    mapOf("name" to "Gem Hoevelhof"),
    mapOf("name" to "Gem Titz"),
    mapOf("name" to "Gem Koeln"),
    mapOf("name" to "Gem Preu?sch Oldendorf"),
    mapOf("name" to "Gem Minden"),
    mapOf("name" to "Gem Krefeld"),
    mapOf("name" to "Gem Lennestadt"),
    mapOf("name" to "Gem Brakel"),
    mapOf("name" to "Gem Alfter"),
    mapOf("name" to "Gem Lohmar"),
    mapOf("name" to "Gem Rosendahl"),
    mapOf("name" to "Gem Velen"),
    mapOf("name" to "Gem Kierspe"),
    mapOf("name" to "Gem Schlo?Holte-Stukenbrock"),
    mapOf("name" to "Gem Bueren"),
    mapOf("name" to "Gem Gangelt"),
    mapOf("name" to "Gem Hille"),
    mapOf("name" to "Gem Frechen"),
    mapOf("name" to "Gem Nordwalde"),
    mapOf("name" to "Gem Moers"),
    mapOf("name" to "Gem Ratingen"),
    mapOf("name" to "Gem Kamen"),
    mapOf("name" to "Gem Everswinkel"),
    mapOf("name" to "Gem Bedburg-Hau"),
    mapOf("name" to "Gem Huertgenwald"),
    mapOf("name" to "Gem Dorsten"),
    mapOf("name" to "Gem Simmerath"),
    mapOf("name" to "Gem Erkrath"),
    mapOf("name" to "Gem Luedinghausen"),
    mapOf("name" to "Gem Harsewinkel"),
    mapOf("name" to "Gem Toenisvorst"),
    mapOf("name" to "Gem Aldenhoven"),
    mapOf("name" to "Gem Billerbeck"),
    mapOf("name" to "Gem Ruppichteroth"),
    mapOf("name" to "Gem Wesel"),
    mapOf("name" to "Gem Heiden"),
    mapOf("name" to "Gem Bergisch Gladbach"),
    mapOf("name" to "Gem Bad Sassendorf"),
    mapOf("name" to "Gem Horn-Bad Meinberg"),
    mapOf("name" to "Gem Monschau"),
    mapOf("name" to "Gem Menden (Sauerland)"),
    mapOf("name" to "Gem Lengerich"),
    mapOf("name" to "Gem Arnsberg"),
    mapOf("name" to "Gem Steinhagen"),
    mapOf("name" to "Gem Luedenscheid"),
    mapOf("name" to "Gem Senden"),
    mapOf("name" to "Gem Grevenbroich"),
    mapOf("name" to "Gem Porta Westfalica"),
    mapOf("name" to "Gem Ostbevern"),
    mapOf("name" to "Gem Langenfeld (Rhld.)"),
    mapOf("name" to "Gem Gladbeck"),
    mapOf("name" to "Gem Kirchlengern"),
    mapOf("name" to "Gem Nuembrecht"),
    mapOf("name" to "Gem Heimbach"),
    mapOf("name" to "Gem Freudenberg"),
    mapOf("name" to "Gem Roedinghausen"),
    mapOf("name" to "Gem Uedem"),
    mapOf("name" to "Gem Swisttal"),
    mapOf("name" to "Gem Kerken"),
    mapOf("name" to "Gem Schieder-Schwalenberg"),
    mapOf("name" to "Gem Goch"),
    mapOf("name" to "Gem Kerpen"),
    mapOf("name" to "Gem Wenden"),
    mapOf("name" to "Gem Bocholt"),
    mapOf("name" to "Gem Kalkar"),
    mapOf("name" to "Gem Werne"),
    mapOf("name" to "Gem Herzebrock-Clarholz"),
    mapOf("name" to "Gem Finnentrop"),
    mapOf("name" to "Gem Werl"),
    mapOf("name" to "Gem Niederkassel"),
    mapOf("name" to "Gem Nieheim"),
    mapOf("name" to "Gem Sprockhoevel"),
    mapOf("name" to "Gem Radevormwald"),
    mapOf("name" to "Gem Roetgen"),
    mapOf("name" to "Gem Boenen"),
    mapOf("name" to "Gem Duesseldorf"),
    mapOf("name" to "Gem Erkelenz"),
    mapOf("name" to "Gem Bergheim"),
    mapOf("name" to "Gem Kall"),
    mapOf("name" to "Gem Espelkamp"),
    mapOf("name" to "Gem Legden"),
    mapOf("name" to "Gem Emmerich am Rhein"),
    mapOf("name" to "Gem Neunkirchen-Seelscheid"),
    mapOf("name" to "Gem Netphen"),
    mapOf("name" to "Gem Anroechte"),
    mapOf("name" to "Gem Recke"),
    mapOf("name" to "Gem Bad Laasphe"),
    mapOf("name" to "Gem Wetter (Ruhr)"),
    mapOf("name" to "Gem Warstein"),
    mapOf("name" to "Gem Kuerten"),
    mapOf("name" to "Gem Wassenberg"),
    mapOf("name" to "Gem Kevelaer"),
    mapOf("name" to "Gem Hemer"),
    mapOf("name" to "Gem Froendenberg/Ruhr"),
    mapOf("name" to "Gem Wilnsdorf"),
    mapOf("name" to "Gem Sundern (Sauerland)"),
    mapOf("name" to "Gem Rhede"),
    mapOf("name" to "Gem Rommerskirchen"),
    mapOf("name" to "Gem Remscheid"),
    mapOf("name" to "Gem Meinerzhagen"),
    mapOf("name" to "Gem Beverungen"),
    mapOf("name" to "Gem Elsdorf"),
    mapOf("name" to "Gem Troisdorf"),
    mapOf("name" to "Gem Alsdorf"),
    mapOf("name" to "Gem Kamp-Lintfort"),
    mapOf("name" to "Gem Hellenthal"),
    mapOf("name" to "Gem Ibbenbueren"),
    mapOf("name" to "Gem Dueren"),
    mapOf("name" to "Gem Bottrop"),
    mapOf("name" to "Gem Viersen"),
    mapOf("name" to "Gem Borchen"),
    mapOf("name" to "Gem Hattingen"),
    mapOf("name" to "Gem Lemgo"),
    mapOf("name" to "Gem Kreuztal"),
    mapOf("name" to "Gem Soest"),
    mapOf("name" to "Gem Schoeppingen"),
    mapOf("name" to "Gem Halver"),
    mapOf("name" to "Gem Verl"),
    mapOf("name" to "Gem Juelich"),
    mapOf("name" to "Gem Neuenrade"),
    mapOf("name" to "Gem Emsdetten"),
    mapOf("name" to "Gem Bad Wuennenberg"),
    mapOf("name" to "Gem Detmold"),
    mapOf("name" to "Gem Beckum"),
    mapOf("name" to "Gem Eslohe (Sauerland)"),
    mapOf("name" to "Gem Guetersloh"),
    mapOf("name" to "Gem Bad Muenstereifel"),
    mapOf("name" to "Gem Borgholzhausen"),
    mapOf("name" to "Gem Ascheberg"),
    mapOf("name" to "Gem Witten"),
    mapOf("name" to "Gem Bad Oeynhausen"),
    mapOf("name" to "Gem Hagen"),
    mapOf("name" to "Gem Mechernich"),
    mapOf("name" to "Gem Bestwig"),
    mapOf("name" to "Gem Kalletal"),
    mapOf("name" to "Gem Westerkappeln"),
    mapOf("name" to "Gem Weilerswist"),
    mapOf("name" to "Gem Morsbach"),
    mapOf("name" to "Gem Steinfurt"),
    mapOf("name" to "Gem Warendorf"),
    mapOf("name" to "Gem Overath"),
    mapOf("name" to "Gem Willich"),
    mapOf("name" to "Gem Havixbeck"),
    mapOf("name" to "Gem Rees"),
    mapOf("name" to "Gem Waltrop"),
    mapOf("name" to "Gem Herscheid"),
    mapOf("name" to "Gem Vreden"),
    mapOf("name" to "Gem Windeck"),
    mapOf("name" to "Gem Wipperfuerth"),
    mapOf("name" to "Gem Olsberg"),
    mapOf("name" to "Gem Ennigerloh"),
    mapOf("name" to "Gem Moehnesee"),
    mapOf("name" to "Gem Moenchengladbach"),
    mapOf("name" to "Gem Greven"),
    mapOf("name" to "Gem Erndtebrueck"),
    mapOf("name" to "Gem Alpen"),
    mapOf("name" to "Gem Lienen"),
    mapOf("name" to "Gem Rheine"),
    mapOf("name" to "Gem Werdohl"),
    mapOf("name" to "Gem Bad Lippspringe"),
    mapOf("name" to "Gem Hallenberg"),
    mapOf("name" to "Gem Neuss"),
    mapOf("name" to "Gem Meerbusch"),
    mapOf("name" to "Gem Rheurdt"),
    mapOf("name" to "Gem Dinslaken"),
    mapOf("name" to "Gem Olpe"),
    mapOf("name" to "Gem Hamm"),
    mapOf("name" to "Gem Bergkamen"),
    mapOf("name" to "Gem Nottuln"),
    mapOf("name" to "Gem Roesrath"),
    mapOf("name" to "Gem Langerwehe"),
    mapOf("name" to "Gem Drolshagen"),
    mapOf("name" to "Gem Pulheim"),
    mapOf("name" to "Gem Hilden"),
    mapOf("name" to "Gem Korschenbroich"),
    mapOf("name" to "Gem Ruethen"),
    mapOf("name" to "Gem Iserlohn"),
    mapOf("name" to "Gem Rietberg"),
    mapOf("name" to "Gem Neuenkirchen"),
    mapOf("name" to "Gem Oberhausen"),
    mapOf("name" to "Gem Enger"),
    mapOf("name" to "Gem Eschweiler"),
    mapOf("name" to "Gem Duisburg"),
    mapOf("name" to "Gem Oerlinghausen"),
    mapOf("name" to "Gem Hueckeswagen"),
    mapOf("name" to "Gem Bad Salzuflen"),
    mapOf("name" to "Gem Inden"),
    mapOf("name" to "Gem Wiehl"),
    mapOf("name" to "Gem Blankenheim"),
    mapOf("name" to "Gem Altena"),
    mapOf("name" to "Gem Issum"),
    mapOf("name" to "Gem Bornheim"),
    mapOf("name" to "Gem Kranenburg"),
    mapOf("name" to "Gem Petershagen"),
    mapOf("name" to "Gem Hoerstel"),
    mapOf("name" to "Gem Augustdorf"),
    mapOf("name" to "Gem Sonsbeck"),
    mapOf("name" to "Gem Schmallenberg"),
    mapOf("name" to "Gem Marienheide"),
    mapOf("name" to "Gem Nideggen"),
    mapOf("name" to "Gem Herten"),
    mapOf("name" to "Gem Zuelpich"),
    mapOf("name" to "Gem Dormagen"),
    mapOf("name" to "Gem Bochum"),
    mapOf("name" to "Gem Balve"),
    mapOf("name" to "Gem Beelen"),
    mapOf("name" to "Gem Juechen"),
    mapOf("name" to "Gem Grefrath"),
    mapOf("name" to "Gem Merzenich"),
    mapOf("name" to "Gem Olfen"),
    mapOf("name" to "Gem Delbrueck"),
    mapOf("name" to "Gem Wesseling"),
    mapOf("name" to "Gem Holzwickede"),
    mapOf("name" to "Gem Duelmen"),
    mapOf("name" to "Gem Nachrodt-Wiblingwerde"),
    mapOf("name" to "Gem Schwelm"),
    mapOf("name" to "Gem Heinsberg"),
    mapOf("name" to "Gem Xanten"),
    mapOf("name" to "Gem Burscheid"),
    mapOf("name" to "Gem Schleiden"),
    mapOf("name" to "Gem Noervenich"),
    mapOf("name" to "Gem Leichlingen (Rhld.)"),
    mapOf("name" to "Gem Metelen"),
    mapOf("name" to "Gem Suedlohn"),
    mapOf("name" to "Gem Medebach"),
    mapOf("name" to "Gem Leopoldshoehe"),
    mapOf("name" to "Gem Wermelskirchen"),
    mapOf("name" to "Gem Bedburg"),
    mapOf("name" to "Gem Geldern"),
    mapOf("name" to "Gem Telgte"),
    mapOf("name" to "Gem Schalksmuehle"),
    mapOf("name" to "Gem Halle (Westf.)"),
    mapOf("name" to "Gem Meckenheim"),
    mapOf("name" to "Gem Vettwei?"),
    mapOf("name" to "Gem Extertal"),
    mapOf("name" to "Gem Schwerte"),
    mapOf("name" to "Gem Euskirchen"),
    mapOf("name" to "Gem Geseke"),
    mapOf("name" to "Gem Steinheim"),
    mapOf("name" to "Gem Rheinbach"),
    mapOf("name" to "Gem Buende"),
    mapOf("name" to "Gem Stadtlohn"),
    mapOf("name" to "Gem Mettingen"),
    mapOf("name" to "Gem Ennepetal"),
    mapOf("name" to "Gem Langenberg"),
    mapOf("name" to "Gem Reken"),
    mapOf("name" to "Gem Altenberge"),
    mapOf("name" to "Gem Koenigswinter"),
    mapOf("name" to "Gem Erftstadt"),
    mapOf("name" to "Gem Wettringen"),
    mapOf("name" to "Gem Schermbeck"),
    mapOf("name" to "Gem Gelsenkirchen"),
    mapOf("name" to "Gem Borken"),
    mapOf("name" to "Gem Eitorf"),
    mapOf("name" to "Gem Meschede"),
    mapOf("name" to "Gem Reichshof"),
    mapOf("name" to "Gem Marienmuenster"),
    mapOf("name" to "Gem Solingen"),
    mapOf("name" to "Gem Leverkusen"),
    mapOf("name" to "Gem Baesweiler"),
    mapOf("name" to "Gem Oelde"),
    mapOf("name" to "Gem Warburg"),
    mapOf("name" to "Gem Huellhorst"),
    mapOf("name" to "Gem Bielefeld"),
    mapOf("name" to "Gem Hamminkeln"),
    mapOf("name" to "Gem Burbach"),
    mapOf("name" to "Gem Nettetal"),
    mapOf("name" to "Gem Loehne"),
    mapOf("name" to "Gem Gronau (Westf.)"),
    mapOf("name" to "Gem Muelheim an der Ruhr"),
    mapOf("name" to "Gem Plettenberg"),
    mapOf("name" to "Gem Dahlem"),
    mapOf("name" to "Gem Altenbeken"),
    mapOf("name" to "Gem Sendenhorst"),
    mapOf("name" to "Gem Rheinberg"),
    mapOf("name" to "Gem Sassenberg"),
    mapOf("name" to "Gem Monheim am Rhein"),
    mapOf("name" to "Gem Welver"),
    mapOf("name" to "Gem Waldbroel"),
    mapOf("name" to "Gem Hiddenhausen"),
    mapOf("name" to "Gem ?ach-Palenberg"),
    mapOf("name" to "Gem Bad Driburg"),
    mapOf("name" to "Gem Erwitte"),
    mapOf("name" to "Gem Siegen"),
    mapOf("name" to "Gem Niederkruechten"),
    mapOf("name" to "Gem Linnich"),
    mapOf("name" to "Gem Recklinghausen"),
    mapOf("name" to "Gem Luenen"),
    mapOf("name" to "Gem Engelskirchen"),
    mapOf("name" to "Gem Hoexter"),
    mapOf("name" to "Gem Versmold"),
    mapOf("name" to "Gem Hueckelhoven"),
    mapOf("name" to "Gem Herzogenrath"),
    mapOf("name" to "Gem Heek"),
    mapOf("name" to "Gem Marl"),
    mapOf("name" to "Gem Much"),
    mapOf("name" to "Gem Winterberg"),
    mapOf("name" to "Gem Herne"),
    mapOf("name" to "Gem Lippstadt"),
    mapOf("name" to "Gem Bonn"),
    mapOf("name" to "Gem Isselburg"),
    mapOf("name" to "Gem Coesfeld"),
    mapOf("name" to "Gem Blomberg"),
    mapOf("name" to "Gem Wachtendonk"),
    mapOf("name" to "Gem Bergneustadt"),
    mapOf("name" to "Gem Straelen"),
    mapOf("name" to "Gem Heiligenhaus"),
    mapOf("name" to "Gem Raesfeld"),
    mapOf("name" to "Gem Horstmar"),
    mapOf("name" to "Gem Lotte"),
    mapOf("name" to "Gem Lichtenau"),
    mapOf("name" to "Gem Attendorn"),
    mapOf("name" to "Gem Luegde"),
    mapOf("name" to "Gem Selm"),
    mapOf("name" to "Gem Wuelfrath"),
    mapOf("name" to "Gem Haltern am See"),
    mapOf("name" to "Gem Lindlar"),
    mapOf("name" to "Gem Wachtberg"),
    mapOf("name" to "Gem Gescher"),
    mapOf("name" to "Gem Kreuzau"),
    mapOf("name" to "Gem Essen"),
    mapOf("name" to "Gem Hopsten"),
    mapOf("name" to "Gem Brueggen"),
    mapOf("name" to "Gem Huenxe"),
    mapOf("name" to "Gem Wuppertal"),
    mapOf("name" to "Gem Luebbecke"),
    mapOf("name" to "Gem Paderborn"),
    mapOf("name" to "Gem Kirchhundem"),
    mapOf("name" to "Gem Selfkant"),
    mapOf("name" to "Gem Vlotho"),
    mapOf("name" to "Gem Borgentreich"),
    mapOf("name" to "Gem Rahden"),
    mapOf("name" to "Gem Wickede (Ruhr)"),
    mapOf("name" to "Gem Huerth"),
    mapOf("name" to "Gem Nettersheim"),
    mapOf("name" to "Gem Ense"),
    mapOf("name" to "Gem Bruehl"),
    mapOf("name" to "Gem Herdecke"),
    mapOf("name" to "Gem Ahlen"),
    mapOf("name" to "Gem Ochtrup"),
    mapOf("name" to "Gem Wadersloh"),
    mapOf("name" to "Gem Wuerselen"),
    mapOf("name" to "Gem Schlangen"),
    mapOf("name" to "Gem Gevelsberg"),
    mapOf("name" to "Gem Voerde (Niederrhein)"),
    mapOf("name" to "Gem Dortmund"),
    mapOf("name" to "Gem Sankt Augustin"),
    mapOf("name" to "Gem Stolberg (Rhld.)"),
    mapOf("name" to "Gem Wegberg"),
    mapOf("name" to "Gem Spenge"),
    mapOf("name" to "Gem Ladbergen"),
    mapOf("name" to "Gem Hilchenbach"),
    mapOf("name" to "Gem Unna"),
    mapOf("name" to "Gem Laer"),
    mapOf("name" to "Gem Niederzier"),
    mapOf("name" to "Gem Oer-Erkenschwick"),
    mapOf("name" to "Gem Datteln"),
    mapOf("name" to "Gem Tecklenburg"),
    mapOf("name" to "Gem Bad Berleburg"),
    mapOf("name" to "Gem Willebadessen"),
    mapOf("name" to "Gem Saerbeck"),
    mapOf("name" to "Gem Lage"),
    mapOf("name" to "Gem Neunkirchen"),
    mapOf("name" to "Gem Herford"),
    mapOf("name" to "Gem Doerentrup"),
    mapOf("name" to "Gem Rheda-Wiedenbrueck"),
    mapOf("name" to "Gem Barntrup"),
    mapOf("name" to "Gem Neukirchen-Vluyn")
)

val counties = listOf(
    mapOf("name" to "Krs Hochsauerlandkreis"),
    mapOf("name" to "Krs Lippe"),
    mapOf("name" to "Krs Rhein-Erft-Kreis"),
    mapOf("name" to "Krs Remscheid"),
    mapOf("name" to "Krs Herne"),
    mapOf("name" to "Krs Duesseldorf"),
    mapOf("name" to "Krs Koeln"),
    mapOf("name" to "Krs Staedteregion Aachen"),
    mapOf("name" to "Krs Wuppertal"),
    mapOf("name" to "Krs Siegen-Wittgenstein"),
    mapOf("name" to "Krs Hagen"),
    mapOf("name" to "Krs Bochum"),
    mapOf("name" to "Krs Bonn"),
    mapOf("name" to "Krs Krefeld"),
    mapOf("name" to "Krs Kleve"),
    mapOf("name" to "Krs Bottrop"),
    mapOf("name" to "Krs Gelsenkirchen"),
    mapOf("name" to "Krs Minden-Luebbecke"),
    mapOf("name" to "Krs Borken"),
    mapOf("name" to "Krs Olpe"),
    mapOf("name" to "Krs Maerkischer Kreis"),
    mapOf("name" to "Krs Recklinghausen"),
    mapOf("name" to "Krs Oberhausen"),
    mapOf("name" to "Krs Soest"),
    mapOf("name" to "Krs Paderborn"),
    mapOf("name" to "Krs Viersen"),
    mapOf("name" to "Krs Steinfurt"),
    mapOf("name" to "Krs Hamm"),
    mapOf("name" to "Krs Essen"),
    mapOf("name" to "Krs Heinsberg"),
    mapOf("name" to "Krs Wesel"),
    mapOf("name" to "Krs Unna"),
    mapOf("name" to "Krs Moenchengladbach"),
    mapOf("name" to "Krs Solingen"),
    mapOf("name" to "Krs Mettmann"),
    mapOf("name" to "Krs Muelheim a.d. Ruhr"),
    mapOf("name" to "Krs Rhein-Sieg-Kreis"),
    mapOf("name" to "Krs Rhein-Kreis Neuss"),
    mapOf("name" to "Krs Dueren"),
    mapOf("name" to "Krs Oberbergischer Kreis"),
    mapOf("name" to "Krs Muenster"),
    mapOf("name" to "Krs Rheinisch-Bergischer Kreis"),
    mapOf("name" to "Krs Duisburg"),
    mapOf("name" to "Krs Bielefeld"),
    mapOf("name" to "Krs Leverkusen"),
    mapOf("name" to "Krs Ennepe-Ruhr-Kreis"),
    mapOf("name" to "Krs Hoexter"),
    mapOf("name" to "Krs Coesfeld"),
    mapOf("name" to "Krs Herford"),
    mapOf("name" to "Krs Dortmund"),
    mapOf("name" to "Krs Warendorf"),
    mapOf("name" to "Krs Guetersloh"),
    mapOf("name" to "Krs Euskirchen")
)

val districts = listOf(
    mapOf("name" to "Rbz Arnsberg"),
    mapOf("name" to "Rbz Detmold"),
    mapOf("name" to "Rbz Koeln"),
    mapOf("name" to "Rbz Duesseldorf"),
    mapOf("name" to "Rbz Muenster")
)

val cities = listOf(
    mapOf("district" to "Aachen", "name" to "Aachen", "population" to "248878"),
    mapOf("district" to "Borken", "name" to "Ahaus", "population" to "39404"),
    mapOf("district" to "Warendorf", "name" to "Ahlen", "population" to "52635"),
    mapOf("district" to "Aachen", "name" to "Alsdorf", "population" to "47330"),
    mapOf("district" to "Maerkischer Kreis", "name" to "Altena", "population" to "16527"),
    mapOf("district" to "Hochsauerlandkreis", "name" to "Arnsberg", "population" to "73487"),
    mapOf("district" to "Olpe", "name" to "Attendorn", "population" to "24330"),
    mapOf("district" to "Siegen-Wittgenstein", "name" to "Bad Berleburg", "population" to "18847"),
    mapOf("district" to "Hoexter", "name" to "Bad Driburg", "population" to "18902"),
    mapOf("district" to "Rhein-Sieg-Kreis", "name" to "Bad Honnef", "population" to "25759"),
    mapOf("district" to "Siegen-Wittgenstein", "name" to "Bad Laasphe", "population" to "13412"),
    mapOf("district" to "Paderborn", "name" to "Bad Lippspringe", "population" to "16408"),
    mapOf("district" to "Euskirchen", "name" to "Bad Muenstereifel", "population" to "17387"),
    mapOf("district" to "Minden-Luebbecke", "name" to "Bad Oeynhausen", "population" to "48535"),
    mapOf("district" to "Lippe", "name" to "Bad Salzuflen", "population" to "54166"),
    mapOf("district" to "Paderborn", "name" to "Bad Wuennenberg", "population" to "12206"),
    mapOf("district" to "Aachen", "name" to "Baesweiler", "population" to "27319"),
    mapOf("district" to "Maerkischer Kreis", "name" to "Balve", "population" to "11217"),
    mapOf("district" to "Lippe", "name" to "Barntrup", "population" to "8501"),
    mapOf("district" to "Warendorf", "name" to "Beckum", "population" to "36637"),
    mapOf("district" to "Rhein-Erft-Kreis", "name" to "Bedburg", "population" to "23743"),
    mapOf("district" to "Rhein-Erft-Kreis", "name" to "Bergheim", "population" to "61749"),
    mapOf("district" to "Rheinisch-Bergischer Kreis", "name" to "Bergisch Gladbach", "population" to "111636"),
    mapOf("district" to "Unna", "name" to "Bergkamen", "population" to "48919"),
    mapOf("district" to "Oberbergischer Kreis", "name" to "Bergneustadt", "population" to "18502"),
    mapOf("district" to "Hoexter", "name" to "Beverungen", "population" to "13064"),
    mapOf("district" to "Urban district", "name" to "Bielefeld", "population" to "333509"),
    mapOf("district" to "Coesfeld", "name" to "Billerbeck", "population" to "11538"),
    mapOf("district" to "Lippe", "name" to "Blomberg", "population" to "15093"),
    mapOf("district" to "Borken", "name" to "Bocholt", "population" to "71061"),
    mapOf("district" to "Urban district", "name" to "Bochum", "population" to "364454"),
    mapOf("district" to "Urban district", "name" to "Bonn", "population" to "330579"),
    mapOf("district" to "Hoexter", "name" to "Borgentreich", "population" to "8501"),
    mapOf("district" to "Guetersloh", "name" to "Borgholzhausen", "population" to "8964"),
    mapOf("district" to "Borken", "name" to "Borken", "population" to "42650"),
    mapOf("district" to "Rhein-Sieg-Kreis", "name" to "Bornheim", "population" to "48348"),
    mapOf("district" to "Urban district", "name" to "Bottrop", "population" to "117388"),
    mapOf("district" to "Hoexter", "name" to "Brakel", "population" to "16125"),
    mapOf("district" to "Ennepe-Ruhr-Kreis", "name" to "Breckerfeld", "population" to "8912"),
    mapOf("district" to "Hochsauerlandkreis", "name" to "Brilon", "population" to "25336"),
    mapOf("district" to "Rhein-Erft-Kreis", "name" to "Bruehl", "population" to "43673"),
    mapOf("district" to "Rheinisch-Bergischer Kreis", "name" to "Burscheid", "population" to "18527"),
    mapOf("district" to "Herford", "name" to "Buende", "population" to "45376"),
    mapOf("district" to "Paderborn", "name" to "Bueren", "population" to "21452"),
    mapOf("district" to "Recklinghausen", "name" to "Castrop-Rauxel", "population" to "73126"),
    mapOf("district" to "Coesfeld", "name" to "Coesfeld", "population" to "36182"),
    mapOf("district" to "Urban districts of Germany", "name" to "Cologne", "population" to "1083498"),
    mapOf("district" to "Recklinghausen", "name" to "Datteln", "population" to "34714"),
    mapOf("district" to "Paderborn", "name" to "Delbrueck", "population" to "32039"),
    mapOf("district" to "Lippe", "name" to "Detmold", "population" to "74097"),
    mapOf("district" to "Wesel", "name" to "Dinslaken", "population" to "67338"),
    mapOf("district" to "Rhein-Kreis Neuss", "name" to "Dormagen", "population" to "64500"),
    mapOf("district" to "Recklinghausen", "name" to "Dorsten", "population" to "74515"),
    mapOf("district" to "Urban district", "name" to "Dortmund", "population" to "587696"),
    mapOf("district" to "Warendorf", "name" to "Drensteinfurt", "population" to "15540"),
    mapOf("district" to "Olpe", "name" to "Drolshagen", "population" to "11640"),
    mapOf("district" to "Urban district", "name" to "Duisburg", "population" to "495885"),
    mapOf("district" to "Coesfeld", "name" to "Duelmen", "population" to "46706"),
    mapOf("district" to "Dueren", "name" to "Dueren", "population" to "91272"),
    mapOf("district" to "", "name" to "Duesseldorf", "population" to "620523"),
    mapOf("district" to "Rhein-Erft-Kreis", "name" to "Elsdorf", "population" to "21745"),
    mapOf("district" to "Kleve", "name" to "Emmerich", "population" to "30869"),
    mapOf("district" to "Steinfurt", "name" to "Emsdetten", "population" to "36068"),
    mapOf("district" to "Herford", "name" to "Enger", "population" to "20469"),
    mapOf("district" to "Ennepe-Ruhr-Kreis", "name" to "Ennepetal", "population" to "30117"),
    mapOf("district" to "Warendorf", "name" to "Ennigerloh", "population" to "19554"),
    mapOf("district" to "Rhein-Erft-Kreis", "name" to "Erftstadt", "population" to "50060"),
    mapOf("district" to "Heinsberg", "name" to "Erkelenz", "population" to "43275"),
    mapOf("district" to "Mettmann", "name" to "Erkrath", "population" to "43878"),
    mapOf("district" to "Soest", "name" to "Erwitte", "population" to "16117"),
    mapOf("district" to "Aachen", "name" to "Eschweiler", "population" to "56172"),
    mapOf("district" to "Minden-Luebbecke", "name" to "Espelkamp", "population" to "24676"),
    mapOf("district" to "Urban district", "name" to "Essen", "population" to "582415"),
    mapOf("district" to "Euskirchen", "name" to "Euskirchen", "population" to "58466"),
    mapOf("district" to "Rhein-Erft-Kreis", "name" to "Frechen", "population" to "51947"),
    mapOf("district" to "Siegen-Wittgenstein", "name" to "Freudenberg", "population" to "17729"),
    mapOf("district" to "Unna", "name" to "Froendenberg", "population" to "20566"),
    mapOf("district" to "Heinsberg", "name" to "Geilenkirchen", "population" to "27518"),
    mapOf("district" to "Kleve", "name" to "Geldern", "population" to "33760"),
    mapOf("district" to "Urban district", "name" to "Gelsenkirchen", "population" to "259105"),
    mapOf("district" to "Borken", "name" to "Gescher", "population" to "17246"),
    mapOf("district" to "Soest", "name" to "Geseke", "population" to "21422"),
    mapOf("district" to "Ennepe-Ruhr-Kreis", "name" to "Gevelsberg", "population" to "30733"),
    mapOf("district" to "Recklinghausen", "name" to "Gladbeck", "population" to "75518"),
    mapOf("district" to "Kleve", "name" to "Goch", "population" to "34531"),
    mapOf("district" to "Rhein-Kreis Neuss", "name" to "Grevenbroich", "population" to "63941"),
    mapOf("district" to "Steinfurt", "name" to "Greven", "population" to "37709"),
    mapOf("district" to "Borken", "name" to "Gronau", "population" to "48576"),
    mapOf("district" to "Oberbergischer Kreis", "name" to "Gummersbach", "population" to "50978"),
    mapOf("district" to "Guetersloh", "name" to "Guetersloh", "population" to "100664"),
    mapOf("district" to "Mettmann", "name" to "Haan", "population" to "30263"),
    mapOf("district" to "Urban district", "name" to "Hagen", "population" to "188687"),
    mapOf("district" to "Hochsauerlandkreis", "name" to "Hallenberg", "population" to "4490"),
    mapOf("district" to "Guetersloh", "name" to "Halle", "population" to "21448"),
    mapOf("district" to "Recklinghausen", "name" to "Haltern am See", "population" to "37845"),
    mapOf("district" to "Maerkischer Kreis", "name" to "Halver", "population" to "16108"),
    mapOf("district" to "Wesel", "name" to "Hamminkeln", "population" to "26962"),
    mapOf("district" to "Urban district", "name" to "Hamm", "population" to "178967"),
    mapOf("district" to "Guetersloh", "name" to "Harsewinkel", "population" to "25338"),
    mapOf("district" to "Ennepe-Ruhr-Kreis", "name" to "Hattingen", "population" to "54278"),
    mapOf("district" to "Mettmann", "name" to "Heiligenhaus", "population" to "26301"),
    mapOf("district" to "Dueren", "name" to "Heimbach", "population" to "4312"),
    mapOf("district" to "Heinsberg", "name" to "Heinsberg", "population" to "42476"),
    mapOf("district" to "Maerkischer Kreis", "name" to "Hemer", "population" to "33863"),
    mapOf("district" to "Rhein-Sieg-Kreis", "name" to "Hennef", "population" to "47544"),
    mapOf("district" to "Ennepe-Ruhr-Kreis", "name" to "Herdecke", "population" to "22653"),
    mapOf("district" to "Herford", "name" to "Herford", "population" to "66495"),
    mapOf("district" to "Urban district", "name" to "Herne city", "population" to "156940"),
    mapOf("district" to "Recklinghausen", "name" to "Herten", "population" to "61860"),
    mapOf("district" to "Aachen", "name" to "Herzogenrath", "population" to "46225"),
    mapOf("district" to "Siegen-Wittgenstein", "name" to "Hilchenbach", "population" to "14646"),
    mapOf("district" to "Mettmann", "name" to "Hilden", "population" to "55274"),
    mapOf("district" to "Lippe", "name" to "Horn-Bad Meinberg", "population" to "17245"),
    mapOf("district" to "Steinfurt", "name" to "Horstmar", "population" to "6595"),
    mapOf("district" to "Steinfurt", "name" to "Hoerstel", "population" to "20335"),
    mapOf("district" to "Hoexter", "name" to "Hoexter", "population" to "28509"),
    mapOf("district" to "Heinsberg", "name" to "Hueckelhoven", "population" to "40425"),
    mapOf("district" to "Oberbergischer Kreis", "name" to "Hueckeswagen", "population" to "14810"),
    mapOf("district" to "Rhein-Erft-Kreis", "name" to "Huerth", "population" to "59525"),
    mapOf("district" to "Steinfurt", "name" to "Ibbenbueren", "population" to "51526"),
    mapOf("district" to "Maerkischer Kreis", "name" to "Iserlohn", "population" to "91815"),
    mapOf("district" to "Borken", "name" to "Isselburg", "population" to "10758"),
    mapOf("district" to "Neuss", "name" to "Juechen", "population" to "23516"),
    mapOf("district" to "Dueren", "name" to "Juelich", "population" to "32336"),
    mapOf("district" to "Rhein-Kreis Neuss", "name" to "Kaarst", "population" to "43615"),
    mapOf("district" to "Kleve", "name" to "Kalkar", "population" to "13944"),
    mapOf("district" to "Unna", "name" to "Kamen", "population" to "42875"),
    mapOf("district" to "Wesel", "name" to "Kamp-Lintfort", "population" to "37635"),
    mapOf("district" to "Viersen", "name" to "Kempen", "population" to "34537"),
    mapOf("district" to "Rhein-Erft-Kreis", "name" to "Kerpen", "population" to "65802"),
    mapOf("district" to "Kleve", "name" to "Kevelaer", "population" to "27955"),
    mapOf("district" to "Maerkischer Kreis", "name" to "Kierspe", "population" to "16089"),
    mapOf("district" to "Kleve", "name" to "Kleve", "population" to "52359"),
    mapOf("district" to "Rhein-Kreis Neuss", "name" to "Korschenbroich", "population" to "33484"),
    mapOf("district" to "Urban districts of Germany", "name" to "Krefeld", "population" to "226844"),
    mapOf("district" to "Siegen-Wittgenstein", "name" to "Kreuztal", "population" to "30965"),
    mapOf("district" to "Rhein-Sieg-Kreis", "name" to "Koenigswinter", "population" to "41122"),
    mapOf("district" to "Lippe", "name" to "Lage", "population" to "34885"),
    mapOf("district" to "Mettmann", "name" to "Langenfeld", "population" to "59112"),
    mapOf("district" to "Rheinisch-Bergischer Kreis", "name" to "Leichlingen", "population" to "27885"),
    mapOf("district" to "Lippe", "name" to "Lemgo", "population" to "40456"),
    mapOf("district" to "Steinfurt", "name" to "Lengerich", "population" to "22511"),
    mapOf("district" to "Olpe", "name" to "Lennestadt", "population" to "25140"),
    mapOf("district" to "Urban district", "name" to "Leverkusen", "population" to "163905"),
    mapOf("district" to "Paderborn", "name" to "Lichtenau", "population" to "10551"),
    mapOf("district" to "Dueren", "name" to "Linnich", "population" to "12697"),
    mapOf("district" to "Soest", "name" to "Lippstadt", "population" to "67793"),
    mapOf("district" to "Rhein-Sieg-Kreis", "name" to "Lohmar", "population" to "30316"),
    mapOf("district" to "Herford", "name" to "Loehne", "population" to "39871"),
    mapOf("district" to "Minden-Luebbecke", "name" to "Luebbecke", "population" to "25573"),
    mapOf("district" to "Maerkischer Kreis", "name" to "Luedenscheid", "population" to "71911"),
    mapOf("district" to "Coesfeld", "name" to "Luedinghausen", "population" to "24810"),
    mapOf("district" to "Lippe", "name" to "Luegde", "population" to "9235"),
    mapOf("district" to "Unna", "name" to "Luenen", "population" to "85838"),
    mapOf("district" to "Hoexter", "name" to "Marienmuenster", "population" to "4903"),
    mapOf("district" to "Recklinghausen", "name" to "Marl", "population" to "84312"),
    mapOf("district" to "Hochsauerlandkreis", "name" to "Marsberg", "population" to "19488"),
    mapOf("district" to "Euskirchen", "name" to "Mechernich", "population" to "27986"),
    mapOf("district" to "Rhein-Sieg-Kreis", "name" to "Meckenheim", "population" to "24741"),
    mapOf("district" to "Hochsauerlandkreis", "name" to "Medebach", "population" to "7987"),
    mapOf("district" to "Rhein-Kreis Neuss", "name" to "Meerbusch", "population" to "56479"),
    mapOf("district" to "Maerkischer Kreis", "name" to "Meinerzhagen", "population" to "20529"),
    mapOf("district" to "Maerkischer Kreis", "name" to "Menden", "population" to "52452"),
    mapOf("district" to "Hochsauerlandkreis", "name" to "Meschede", "population" to "29696"),
    mapOf("district" to "Mettmann", "name" to "Mettmann", "population" to "38749"),
    mapOf("district" to "Minden-Luebbecke", "name" to "Minden", "population" to "81592"),
    mapOf("district" to "Wesel", "name" to "Moers", "population" to "103487"),
    mapOf("district" to "Mettmann", "name" to "Monheim am Rhein", "population" to "41279"),
    mapOf("district" to "Aachen", "name" to "Monschau", "population" to "11686"),
    mapOf("district" to "Urban districts of Germany", "name" to "Moenchengladbach", "population" to "259665"),
    mapOf("district" to "Urban districts of Germany", "name" to "Muelheim an der Ruhr", "population" to "170921"),
    mapOf("district" to "Urban district", "name" to "Muenster", "population" to "316403"),
    mapOf("district" to "Siegen-Wittgenstein", "name" to "Netphen", "population" to "23033"),
    mapOf("district" to "Viersen", "name" to "Nettetal", "population" to "42438"),
    mapOf("district" to "Maerkischer Kreis", "name" to "Neuenrade", "population" to "11772"),
    mapOf("district" to "Wesel", "name" to "Neukirchen-Vluyn", "population" to "27532"),
    mapOf("district" to "Rhein-Kreis Neuss", "name" to "Neuss", "population" to "153109"),
    mapOf("district" to "Dueren", "name" to "Nideggen", "population" to "10155"),
    mapOf("district" to "Rhein-Sieg-Kreis", "name" to "Niederkassel", "population" to "38512"),
    mapOf("district" to "Hoexter", "name" to "Nieheim", "population" to "6026"),
    mapOf("district" to "Urban districts of Germany", "name" to "Oberhausen", "population" to "209566"),
    mapOf("district" to "Steinfurt", "name" to "Ochtrup", "population" to "19673"),
    mapOf("district" to "Warendorf", "name" to "Oelde", "population" to "29133"),
    mapOf("district" to "Recklinghausen", "name" to "Oer-Erkenschwick", "population" to "31532"),
    mapOf("district" to "Lippe", "name" to "Oerlinghausen", "population" to "17065"),
    mapOf("district" to "Coesfeld", "name" to "Olfen", "population" to "13014"),
    mapOf("district" to "Olpe", "name" to "Olpe", "population" to "24593"),
    mapOf("district" to "Hochsauerlandkreis", "name" to "Olsberg", "population" to "21452"),
    mapOf("district" to "Rheinisch-Bergischer Kreis", "name" to "Overath", "population" to "27124"),
    mapOf("district" to "Paderborn", "name" to "Paderborn", "population" to "151864"),
    mapOf("district" to "Minden-Luebbecke", "name" to "Petershagen", "population" to "25045"),
    mapOf("district" to "Maerkischer Kreis", "name" to "Plettenberg", "population" to "24978"),
    mapOf("district" to "Minden-Luebbecke", "name" to "Porta Westfalica", "population" to "35734"),
    mapOf("district" to "Minden-Luebbecke", "name" to "Preußisch Oldendorf", "population" to "12236"),
    mapOf("district" to "Rhein-Erft-Kreis", "name" to "Pulheim", "population" to "54636"),
    mapOf("district" to "Oberbergischer Kreis", "name" to "Radevormwald", "population" to "21963"),
    mapOf("district" to "Minden-Luebbecke", "name" to "Rahden", "population" to "15404"),
    mapOf("district" to "Mettmann", "name" to "Ratingen", "population" to "86899"),
    mapOf("district" to "Recklinghausen", "name" to "Recklinghausen", "population" to "110705"),
    mapOf("district" to "Kleve", "name" to "Rees", "population" to "21030"),
    mapOf("district" to "Urban districts of Germany", "name" to "Remscheid", "population" to "111516"),
    mapOf("district" to "Guetersloh", "name" to "Rheda-Wiedenbrueck", "population" to "48672"),
    mapOf("district" to "Borken", "name" to "Rhede", "population" to "19319"),
    mapOf("district" to "Rhein-Sieg-Kreis", "name" to "Rheinbach", "population" to "26949"),
    mapOf("district" to "Wesel", "name" to "Rheinberg", "population" to "30933"),
    mapOf("district" to "Steinfurt", "name" to "Rheine", "population" to "76123"),
    mapOf("district" to "Guetersloh", "name" to "Rietberg", "population" to "29432"),
    mapOf("district" to "Rheinisch-Bergischer Kreis", "name" to "Roesrath", "population" to "28759"),
    mapOf("district" to "Soest", "name" to "Ruethen", "population" to "10565"),
    mapOf("district" to "Paderborn", "name" to "Salzkotten", "population" to "25013"),
    mapOf("district" to "Rhein-Sieg-Kreis", "name" to "Sankt Augustin", "population" to "55590"),
    mapOf("district" to "Warendorf", "name" to "Sassenberg", "population" to "14215"),
    mapOf("district" to "Lippe", "name" to "Schieder-Schwalenberg", "population" to "8355"),
    mapOf("district" to "Euskirchen", "name" to "Schleiden", "population" to "13191"),
    mapOf("district" to "Guetersloh", "name" to "Schloß Holte-Stukenbrock", "population" to "26943"),
    mapOf("district" to "Hochsauerlandkreis", "name" to "Schmallenberg", "population" to "24806"),
    mapOf("district" to "Ennepe-Ruhr-Kreis", "name" to "Schwelm", "population" to "28590"),
    mapOf("district" to "Unna", "name" to "Schwerte", "population" to "46124"),
    mapOf("district" to "Unna", "name" to "Selm", "population" to "25802"),
    mapOf("district" to "Warendorf", "name" to "Sendenhorst", "population" to "13289"),
    mapOf("district" to "Rhein-Sieg-Kreis", "name" to "Siegburg", "population" to "41669"),
    mapOf("district" to "Siegen-Wittgenstein", "name" to "Siegen", "population" to "101943"),
    mapOf("district" to "Soest", "name" to "Soest", "population" to "47206"),
    mapOf("district" to "Urban district", "name" to "Solingen", "population" to "159193"),
    mapOf("district" to "Herford", "name" to "Spenge", "population" to "14419"),
    mapOf("district" to "Ennepe-Ruhr-Kreis", "name" to "Sprockhoevel", "population" to "24702"),
    mapOf("district" to "Borken", "name" to "Stadtlohn", "population" to "20290"),
    mapOf("district" to "Steinfurt", "name" to "Steinfurt", "population" to "34431"),
    mapOf("district" to "Hoexter", "name" to "Steinheim", "population" to "12617"),
    mapOf("district" to "Aachen", "name" to "Stolberg", "population" to "56377"),
    mapOf("district" to "Kleve", "name" to "Straelen", "population" to "16248"),
    mapOf("district" to "Hochsauerlandkreis", "name" to "Sundern", "population" to "27554"),
    mapOf("district" to "Steinfurt", "name" to "Tecklenburg", "population" to "9138"),
    mapOf("district" to "Warendorf", "name" to "Telgte", "population" to "19841"),
    mapOf("district" to "Rhein-Sieg-Kreis", "name" to "Troisdorf", "population" to "74994"),
    mapOf("district" to "Viersen", "name" to "Toenisvorst", "population" to "29249"),
    mapOf("district" to "Unna", "name" to "Unna", "population" to "58816"),
    mapOf("district" to "Mettmann", "name" to "Velbert", "population" to "81564"),
    mapOf("district" to "Borken", "name" to "Velen", "population" to "13112"),
    mapOf("district" to "Guetersloh", "name" to "Verl", "population" to "25382"),
    mapOf("district" to "Guetersloh", "name" to "Versmold", "population" to "21697"),
    mapOf("district" to "Viersen", "name" to "Viersen", "population" to "77376"),
    mapOf("district" to "Herford", "name" to "Vlotho", "population" to "18384"),
    mapOf("district" to "Wesel", "name" to "Voerde", "population" to "36047"),
    mapOf("district" to "Borken", "name" to "Vreden", "population" to "22676"),
    mapOf("district" to "Oberbergischer Kreis", "name" to "Waldbroel", "population" to "19599"),
    mapOf("district" to "Recklinghausen", "name" to "Waltrop", "population" to "29472"),
    mapOf("district" to "Hoexter", "name" to "Warburg", "population" to "22928"),
    mapOf("district" to "Warendorf", "name" to "Warendorf", "population" to "37173"),
    mapOf("district" to "Soest", "name" to "Warstein", "population" to "24520"),
    mapOf("district" to "Heinsberg", "name" to "Wassenberg", "population" to "18830"),
    mapOf("district" to "Heinsberg", "name" to "Wegberg", "population" to "28130"),
    mapOf("district" to "Maerkischer Kreis", "name" to "Werdohl", "population" to "17660"),
    mapOf("district" to "Soest", "name" to "Werl", "population" to "30702"),
    mapOf("district" to "Rheinisch-Bergischer Kreis", "name" to "Wermelskirchen", "population" to "34597"),
    mapOf("district" to "Unna", "name" to "Werne", "population" to "29588"),
    mapOf("district" to "Guetersloh", "name" to "Werther (Westf.)", "population" to "11091"),
    mapOf("district" to "Wesel", "name" to "Wesel", "population" to "60329"),
    mapOf("district" to "Rhein-Erft-Kreis", "name" to "Wesseling", "population" to "36731"),
    mapOf("district" to "Ennepe-Ruhr-Kreis", "name" to "Wetter", "population" to "27269"),
    mapOf("district" to "Oberbergischer Kreis", "name" to "Wiehl", "population" to "25199"),
    mapOf("district" to "Hoexter", "name" to "Willebadessen", "population" to "8154"),
    mapOf("district" to "Viersen", "name" to "Willich", "population" to "50283"),
    mapOf("district" to "Hochsauerlandkreis", "name" to "Winterberg", "population" to "12442"),
    mapOf("district" to "Oberbergischer Kreis", "name" to "Wipperfuerth", "population" to "20875"),
    mapOf("district" to "Ennepe-Ruhr-Kreis", "name" to "Witten", "population" to "95876"),
    mapOf("district" to "Urban district", "name" to "Wuppertal", "population" to "355004"),
    mapOf("district" to "Mettmann", "name" to "Wuelfrath", "population" to "21003"),
    mapOf("district" to "Aachen", "name" to "Wuerselen", "population" to "38496"),
    mapOf("district" to "Wesel", "name" to "Xanten", "population" to "21521"),
    mapOf("district" to "Euskirchen", "name" to "Zuelpich", "population" to "20440"),
    mapOf("district" to "Heinsberg", "name" to "uebach-Palenberg", "population" to "23906")
)